name: datapartnership-gaza-israel-conflict-impact-analysis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bokeh
  - colorcet
  - folium
  - geopandas
  - jupyterlab
  - pandas
  - pip
  - pip:
      - blackmarblepy
