# Book settings
title:
author: Development Data Group
logo: docs/images/logo.png
only_build_toc_files: true

repository:
  url: https://github.com/datapartnership/gaza-israel-conflict-impact-analysis
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://worldbank.github.io/https://github.com/datapartnership/gaza-israel-conflict-impact-analysis
  extra_footer: |
    <div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://raw.githubusercontent.com/worldbank/template/main/LICENSE">World Bank Master Community License Agreement.</a></b>
    </div>

#######################################################################################
# Execution settings
execute:
  execute_notebooks: "off"

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
